#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_etcd_server="0.0.1"
  jq -n --arg etcd_server "$ver_etcd_server" '{etcd_server: $etcd_server}'
}

version "$@"
